import { Continent } from './models/db/continent.model';
import { Country } from './models/db/country.model';
import { State } from './models/db/state.model';
import { City } from './models/db/city.model';
import { Suburb } from './models/db/suburb.model';
import { BaseAddress } from './models/db/base-address.model';
import { BusinessAddress } from './models/db/business-address.model';
import { ApartmentAddress } from './models/db/apartment-address.model';
import { FarmAddress } from './models/db/farm-address.model';

import { sequelize } from './services/sequelize.service';

export function migrate() {
    sequelize.addModels([Continent, Country, State, City, Suburb, BaseAddress, ApartmentAddress, BusinessAddress, FarmAddress]);

    migrateContinent()
        .then(migrateCountry)
        .then(migrateState)
        .then(migrateCity)
        .then(migrateSuburb)
        .then(migrateBaseAddress)
        .then(migrateApartmentAddress)
        .then(migrateBusinessAddress)
        .then(migrateFarmAddress);

}

function migrateContinent() {
    return Continent.sync({ force: true }).then(() => Continent.bulkCreate([
        { name: "Africa" },
        { name: "Asia" },
        { name: "Europe" },
        { name: "North America" },
        { name: "South America" },
        { name: "Oceana" },
        { name: "Antarctica" }
    ]))
}

function migrateCountry() {
    return Country.sync({ force: true }).then(() => Country.bulkCreate([
        { name: "Afghanistan", continentId: 2, population: 37209007, landArea: 652860.00 },
        { name: "Albania", continentId: 3, population: 2938428, landArea: 27400.00 },
        { name: "Algeria", continentId: 1, population: 42679018, landArea: 2381740.00 },
        { name: "Andorra", continentId: 3, population: 77072, landArea: 470.00 },
        { name: "Angola", continentId: 1, population: 31787566, landArea: 1246700.00 },
        { name: "Antigua and Barbuda", continentId: 4, population: 104084, landArea: 440.00 },
        { name: "Argentina", continentId: 5, population: 45101781, landArea: 2736690.00 },
        { name: "Armenia", continentId: 3, population: 2936706, landArea: 28470.00 },
        { name: "Australia", continentId: 6, population: 25088636, landArea: 7682300.00 },
        { name: "Austria", continentId: 3, population: 8766201, landArea: 82409.00 },
        { name: "Azerbaijan", continentId: 3, population: 10014575, landArea: 82658.00 },
        { name: "Bahamas", continentId: 4, population: 403095, landArea: 10010.00 },
        { name: "Bahrain", continentId: 2, population: 1637896, landArea: 760.00 },
        { name: "Bangladesh", continentId: 2, population: 168065920, landArea: 130170.00 },
        { name: "Barbados", continentId: 4, population: 287010, landArea: 430.00 },
        { name: "Belarus", continentId: 3, population: 9433874, landArea: 202910.00 },
        { name: "Belgium", continentId: 3, population: 11562784, landArea: 30280.00 },
        { name: "Belize", continentId: 4, population: 390231, landArea: 22810.00 },
        { name: "Benin", continentId: 1, population: 11801595, landArea: 112760.00 },
        { name: "Bhutan", continentId: 2, population: 826229, landArea: 38117.00 },
        { name: "Bolivia", continentId: 5, population: 11379861, landArea: 1083300.00 },
        { name: "Bosnia and Herzegovina", continentId: 3, population: 3501774, landArea: 51000.00 },
        { name: "Botswana", continentId: 1, population: 2374636, landArea: 566730.00 },
        { name: "Brazil", continentId: 5, population: 212392717, landArea: 8358140.00 },
        { name: "Brunei", continentId: 2, population: 439336, landArea: 5270.00 },
        { name: "Bulgaria", continentId: 3, population: 6988739, landArea: 108560.00 },
        { name: "Burkina Faso", continentId: 1, population: 20321560, landArea: 273600.00 },
        { name: "Burundi", continentId: 1, population: 11575964, landArea: 25680.00 },
        { name: "Côte d'Ivoire", continentId: 1, population: 25531083, landArea: 318000.00 },
        { name: "Cabo Verde", continentId: 1, population: 560349, landArea: 4030.00 },
        { name: "Cambodia", continentId: 2, population: 16482646, landArea: 176520.00 },
        { name: "Cameroon", continentId: 1, population: 25312993, landArea: 472710.00 },
        { name: "Canada", continentId: 4, population: 37279811, landArea: 9093510.00 },
        { name: "Central 1n Republic", continentId: 1, population: 4825711, landArea: 622980.00 },
        { name: "Chad", continentId: 1, population: 15814345, landArea: 1259200.00 },
        { name: "Chile", continentId: 5, population: 18336653, landArea: 743532.00 },
        { name: "China", continentId: 2, population: 1420062022, landArea: 9388211.00 },
        { name: "Colombia", continentId: 5, population: 49849818, landArea: 1109500.00 },
        { name: "Comoros", continentId: 1, population: 850910, landArea: 1861.00 },
        { name: "Congo (Congo-Brazzaville)", continentId: 1, population: 5542197, landArea: 341500.00 },
        { name: "Costa Rica", continentId: 4, population: 4999384, landArea: 51060.00 },
        { name: "Croatia", continentId: 3, population: 4140148, landArea: 55960.00 },
        { name: "Cuba", continentId: 4, population: 11492046, landArea: 106440.00 },
        { name: "Cyprus", continentId: 3, population: 1198427, landArea: 9240.00 },
        { name: "Czechia", continentId: 3, population: 10630589, landArea: 77240.00 },
        { name: "Democratic Republic of the Congo", continentId: 1, population: 86727573, landArea: 2267050.00 },
        { name: "Denmark", continentId: 3, population: 5775224, landArea: 42430.00 },
        { name: "Djibouti", continentId: 1, population: 985690, landArea: 23180.00 },
        { name: "Dominica", continentId: 4, population: 74679, landArea: 750.00 },
        { name: "Dominican Republic", continentId: 4, population: 10996774, landArea: 48320.00 },
        { name: "Ecuador", continentId: 5, population: 17100444, landArea: 248360.00 },
        { name: "Egypt", continentId: 1, population: 101168745, landArea: 995450.00 },
        { name: "El Salvador", continentId: 4, population: 6445405, landArea: 20720.00 },
        { name: "Equatorial Guinea", continentId: 1, population: 1360104, landArea: 28050.00 },
        { name: "Eritrea", continentId: 1, population: 5309659, landArea: 101000.00 },
        { name: "Estonia", continentId: 3, population: 1303798, landArea: 42390.00 },
        { name: "Ethiopia", continentId: 1, population: 110135635, landArea: 1000000.00 },
        { name: "Fiji", continentId: 6, population: 918757, landArea: 18270.00 },
        { name: "Finland", continentId: 3, population: 5561389, landArea: 303890.00 },
        { name: "France", continentId: 3, population: 65480710, landArea: 547557.00 },
        { name: "Gabon", continentId: 1, population: 2109099, landArea: 257670.00 },
        { name: "Gambia", continentId: 1, population: 2228075, landArea: 10120.00 },
        { name: "Georgia", continentId: 3, population: 3904204, landArea: 69490.00 },
        { name: "Germany", continentId: 3, population: 82438639, landArea: 348560.00 },
        { name: "Ghana", continentId: 1, population: 30096970, landArea: 227540.00 },
        { name: "Greece", continentId: 3, population: 11124603, landArea: 128900.00 },
        { name: "Grenada", continentId: 4, population: 108825, landArea: 340.00 },
        { name: "Guatemala", continentId: 4, population: 17577842, landArea: 107160.00 },
        { name: "Guinea", continentId: 1, population: 13398180, landArea: 245720.00 },
        { name: "Guinea-Bissau", continentId: 1, population: 1953723, landArea: 28120.00 },
        { name: "Guyana", continentId: 5, population: 786508, landArea: 196850.00 },
        { name: "Haiti", continentId: 4, population: 11242856, landArea: 27560.00 },
        { name: "Holy See", continentId: 4, population: 799, landArea: 0.00 },
        { name: "Honduras", continentId: 3, population: 9568688, landArea: 111890.00 },
        { name: "Hungary", continentId: 3, population: 9655361, landArea: 90530.00 },
        { name: "Iceland", continentId: 2, population: 340566, landArea: 100250.00 },
        { name: "India", continentId: 2, population: 1368737513, landArea: 2973190.00 },
        { name: "Indonesia", continentId: 2, population: 269536482, landArea: 1811570.00 },
        { name: "Iran", continentId: 2, population: 82820766, landArea: 1628550.00 },
        { name: "Iraq", continentId: 3, population: 40412299, landArea: 434320.00 },
        { name: "Ireland", continentId: 2, population: 4847139, landArea: 68890.00 },
        { name: "Israel", continentId: 3, population: 8583916, landArea: 21640.00 },
        { name: "Italy", continentId: 1, population: 59216525, landArea: 294140.00 },
        { name: "Jamaica", continentId: 4, population: 2906339, landArea: 10830.00 },
        { name: "Japan", continentId: 2, population: 126854745, landArea: 364555.00 },
        { name: "Jordan", continentId: 2, population: 10069794, landArea: 88780.00 },
        { name: "Kazakhstan", continentId: 2, population: 18592970, landArea: 2699700.00 },
        { name: "Kenya", continentId: 1, population: 52214791, landArea: 569140.00 },
        { name: "Kiribati", continentId: 6, population: 120428, landArea: 810.00 },
        { name: "Kuwait", continentId: 2, population: 4248974, landArea: 17820.00 },
        { name: "Kyrgyzstan", continentId: 2, population: 6218616, landArea: 191800.00 },
        { name: "Laos", continentId: 2, population: 7064242, landArea: 230800.00 },
        { name: "Latvia", continentId: 3, population: 1911108, landArea: 62200.00 },
        { name: "Lebanon", continentId: 2, population: 6065922, landArea: 10230.00 },
        { name: "Lesotho", continentId: 1, population: 2292682, landArea: 30360.00 },
        { name: "Liberia", continentId: 1, population: 4977720, landArea: 96320.00 },
        { name: "Libya", continentId: 1, population: 6569864, landArea: 1759540.00 },
        { name: "Liechtenstein", continentId: 3, population: 38404, landArea: 160.00 },
        { name: "Lithuania", continentId: 3, population: 2864459, landArea: 62674.00 },
        { name: "Luxembourg", continentId: 3, population: 596992, landArea: 2590.00 },
        { name: "Madagascar", continentId: 1, population: 26969642, landArea: 581795.00 },
        { name: "Malawi", continentId: 1, population: 19718743, landArea: 94280.00 },
        { name: "Malaysia", continentId: 2, population: 32454455, landArea: 328550.00 },
        { name: "Maldives", continentId: 2, population: 451738, landArea: 300.00 },
        { name: "Mali", continentId: 1, population: 19689140, landArea: 1220190.00 },
        { name: "Malta", continentId: 3, population: 433245, landArea: 320.00 },
        { name: "Marshall Islands", continentId: 6, population: 53211, landArea: 180.00 },
        { name: "Mauritania", continentId: 1, population: 4661149, landArea: 1030700.00 },
        { name: "Mauritius", continentId: 1, population: 1271368, landArea: 2030.00 },
        { name: "Mexico", continentId: 4, population: 132328035, landArea: 1943950.00 },
        { name: "Micronesia", continentId: 6, population: 536579, landArea: 700.00 },
        { name: "Moldova", continentId: 3, population: 4029750, landArea: 32850.00 },
        { name: "Monaco", continentId: 3, population: 39102, landArea: 1.00 },
        { name: "Mongolia", continentId: 2, population: 3166244, landArea: 1553560.00 },
        { name: "Montenegro", continentId: 3, population: 629355, landArea: 13450.00 },
        { name: "Morocco", continentId: 1, population: 36635156, landArea: 446300.00 },
        { name: "Mozambique", continentId: 1, population: 31408823, landArea: 786380.00 },
        { name: "Myanmar (formerly Burma)", continentId: 2, population: 54336138, landArea: 653290.00 },
        { name: "Namibia", continentId: 1, population: 2641996, landArea: 823290.00 },
        { name: "Nauru", continentId: 6, population: 11260, landArea: 20.00 },
        { name: "Nepal", continentId: 2, population: 29942018, landArea: 143350.00 },
        { name: "Netherlands", continentId: 3, population: 17132908, landArea: 33720.00 },
        { name: "New Zealand", continentId: 6, population: 4792409, landArea: 263310.00 },
        { name: "Nicaragua", continentId: 4, population: 6351157, landArea: 120340.00 },
        { name: "Niger", continentId: 1, population: 23176691, landArea: 1266700.00 },
        { name: "Nigeria", continentId: 1, population: 200962417, landArea: 910770.00 },
        { name: "North Korea", continentId: 2, population: 25727408, landArea: 120410.00 },
        { name: "North Macedonia", continentId: 3, population: 2086720, landArea: 25220.00 },
        { name: "Norway", continentId: 3, population: 5400916, landArea: 365268.00 },
        { name: "Oman", continentId: 2, population: 5001875, landArea: 309500.00 },
        { name: "Pakistan", continentId: 2, population: 204596442, landArea: 770880.00 },
        { name: "Palau", continentId: 6, population: 22206, landArea: 460.00 },
        { name: "Palestine State", continentId: 2, population: 5186790, landArea: 6020.00 },
        { name: "Panama", continentId: 4, population: 4226197, landArea: 74340.00 },
        { name: "Papua New Guinea", continentId: 6, population: 8586525, landArea: 452860.00 },
        { name: "Paraguay", continentId: 5, population: 6981981, landArea: 397300.00 },
        { name: "Peru", continentId: 5, population: 32933835, landArea: 1280000.00 },
        { name: "Philippines", continentId: 2, population: 108106310, landArea: 298170.00 },
        { name: "Poland", continentId: 3, population: 38028278, landArea: 306230.00 },
        { name: "Portugal", continentId: 3, population: 10254666, landArea: 91590.00 },
        { name: "Qatar", continentId: 2, population: 2743901, landArea: 11610.00 },
        { name: "Romania", continentId: 3, population: 19483360, landArea: 230170.00 },
        { name: "Russia", continentId: 2, population: 143895551, landArea: 16376870.00 },
        { name: "Rwanda", continentId: 1, population: 12794412, landArea: 24670.00 },
        { name: "Saint Kitts and Nevis", continentId: 4, population: 56345, landArea: 260.00 },
        { name: "Saint Lucia", continentId: 4, population: 180454, landArea: 610.00 },
        { name: "Saint Vincent and the Grenadines", continentId: 4, population: 110488, landArea: 390.00 },
        { name: "Samoa", continentId: 6, population: 198909, landArea: 2830.00 },
        { name: "San Marino", continentId: 3, population: 33683, landArea: 60.00 },
        { name: "Sao Tome and Principe", continentId: 1, population: 213379, landArea: 960.00 },
        { name: "Saudi Arabia", continentId: 2, population: 34140662, landArea: 2149690.00 },
        { name: "Senegal", continentId: 1, population: 16743859, landArea: 192530.00 },
        { name: "Serbia", continentId: 3, population: 8733407, landArea: 87460.00 },
        { name: "Seychelles", continentId: 1, population: 95702, landArea: 460.00 },
        { name: "Sierra Leone", continentId: 1, population: 7883123, landArea: 72180.00 },
        { name: "Singapore", continentId: 2, population: 5868104, landArea: 700.00 },
        { name: "Slovakia", continentId: 3, population: 5450987, landArea: 48088.00 },
        { name: "Slovenia", continentId: 3, population: 2081900, landArea: 20140.00 },
        { name: "Solomon Islands", continentId: 6, population: 635254, landArea: 27990.00 },
        { name: "Somalia", continentId: 1, population: 15636171, landArea: 627340.00 },
        { name: "South Africa", continentId: 1, population: 58065097, landArea: 1213090.00 },
        { name: "South Korea", continentId: 2, population: 51339238, landArea: 97230.00 },
        { name: "South Sudan", continentId: 1, population: 13263184, landArea: 610952.00 },
        { name: "Spain", continentId: 3, population: 46441049, landArea: 498800.00 },
        { name: "Sri Lanka", continentId: 2, population: 21018859, landArea: 62710.00 },
        { name: "Sudan", continentId: 1, population: 42514094, landArea: 1765048.00 },
        { name: "Suriname", continentId: 5, population: 573085, landArea: 156000.00 },
        { name: "Swaziland", continentId: 1, population: 1415414, landArea: 17200.00 },
        { name: "Sweden", continentId: 3, population: 10053135, landArea: 410340.00 },
        { name: "Switzerland", continentId: 3, population: 8608259, landArea: 39516.00 },
        { name: "Syria", continentId: 2, population: 18499181, landArea: 183630.00 },
        { name: "Tajikistan", continentId: 2, population: 9292000, landArea: 139960.00 },
        { name: "Tanzania", continentId: 1, population: 60913557, landArea: 885800.00 },
        { name: "Thailand", continentId: 2, population: 69306160, landArea: 510890.00 },
        { name: "Timor-Leste", continentId: 2, population: 1352360, landArea: 14870.00 },
        { name: "Togo", continentId: 1, population: 8186384, landArea: 54390.00 },
        { name: "Tonga", continentId: 6, population: 110041, landArea: 720.00 },
        { name: "Trinidad and Tobago", continentId: 4, population: 1375443, landArea: 5130.00 },
        { name: "Tunisia", continentId: 1, population: 11783168, landArea: 155360.00 },
        { name: "Turkey", continentId: 2, population: 82961805, landArea: 769630.00 },
        { name: "Turkmenistan", continentId: 2, population: 5942561, landArea: 469930.00 },
        { name: "Tuvalu", continentId: 6, population: 11393, landArea: 30.00 },
        { name: "Uganda", continentId: 1, population: 45711874, landArea: 199810.00 },
        { name: "Ukraine", continentId: 3, population: 43795220, landArea: 579320.00 },
        { name: "United Arab Emirates", continentId: 2, population: 9682088, landArea: 83600.00 },
        { name: "United Kingdom", continentId: 3, population: 66959016, landArea: 241930.00 },
        { name: "United States of America", continentId: 4, population: 329093110, landArea: 9147420.00 },
        { name: "Uruguay", continentId: 5, population: 3482156, landArea: 175020.00 },
        { name: "Uzbekistan", continentId: 2, population: 32807368, landArea: 425400.00 },
        { name: "Vanuatu", continentId: 6, population: 288017, landArea: 12190.00 },
        { name: "Vatican City", continentId: 3, population: 799, landArea: 0.44 },
        { name: "Venezuela", continentId: 5, population: 32779868, landArea: 882050.00 },
        { name: "Vietnam", continentId: 2, population: 97429061, landArea: 310070.00 },
        { name: "Yemen", continentId: 2, population: 29579986, landArea: 527970.00 },
        { name: "Zambia", continentId: 1, population: 18137369, landArea: 743390.00 },
        { name: "Zimbabwe", continentId: 1, population: 17297495, landArea: 386850.00 }
    ]));
}

function migrateState() {
    return State.sync({ force: true }).then(() => State.bulkCreate([
        { name: "Eastern Cape", countryId: 161 },
        { name: "Free State", countryId: 161 },
        { name: "Gauteng", countryId: 161 },
        { name: "KwaZulu-Natal", countryId: 161 },
        { name: "Limpopo", countryId: 161 },
        { name: "Mpumalanga", countryId: 161 },
        { name: "North West", countryId: 161 },
        { name: "Northern Cape", countryId: 161 },
        { name: "Western Cape ", countryId: 161 },
        { name: "Alabama", countryId: 187 },
        { name: "Alaska", countryId: 187 },
        { name: "Arizona", countryId: 187 },
        { name: "Arkansas", countryId: 187 },
        { name: "California", countryId: 187 },
        { name: "Colorado", countryId: 187 },
        { name: "Connecticut", countryId: 187 },
        { name: "Delaware", countryId: 187 },
        { name: "Florida", countryId: 187 },
        { name: "Georgia", countryId: 187 },
        { name: "Hawaii", countryId: 187 },
        { name: "Idaho", countryId: 187 },
        { name: "Illinois", countryId: 187 },
        { name: "Indiana", countryId: 187 },
        { name: "Iowa", countryId: 187 },
        { name: "Kansas", countryId: 187 },
        { name: "Kentucky", countryId: 187 },
        { name: "Louisiana", countryId: 187 },
        { name: "Maine", countryId: 187 },
        { name: "Maryland", countryId: 187 },
        { name: "Massachusetts", countryId: 187 },
        { name: "Michigan", countryId: 187 },
        { name: "Minnesota", countryId: 187 },
        { name: "Mississippi", countryId: 187 },
        { name: "Missouri", countryId: 187 },
        { name: "Montana", countryId: 187 },
        { name: "Nebraska", countryId: 187 },
        { name: "Nevada", countryId: 187 },
        { name: "New Hampshire", countryId: 187 },
        { name: "New Jersey", countryId: 187 },
        { name: "New Mexico", countryId: 187 },
        { name: "New York", countryId: 187 },
        { name: "North Carolina", countryId: 187 },
        { name: "North Dakota", countryId: 187 },
        { name: "Ohio", countryId: 187 },
        { name: "Oklahoma", countryId: 187 },
        { name: "Oregon", countryId: 187 },
        { name: "Pennsylvania", countryId: 187 },
        { name: "Rhode Island", countryId: 187 },
        { name: "South Carolina", countryId: 187 },
        { name: "South Dakota", countryId: 187 },
        { name: "Tennessee", countryId: 187 },
        { name: "Texas", countryId: 187 },
        { name: "Utah", countryId: 187 },
        { name: "Vermont", countryId: 187 },
        { name: "Virginia", countryId: 187 },
        { name: "Washington", countryId: 187 },
        { name: "West Virginia", countryId: 187 },
        { name: "Wyoming", countryId: 187 },
        { name: "Wisconsin", countryId: 187 }
    ]));
}


function migrateCity() {
    return City.sync({ force: true }).then(() => City.bulkCreate([
        { name: "Alice", stateId: 1 },
        { name: "Butterworth", stateId: 1 },
        { name: "East London", stateId: 1 },
        { name: "Graaff-Reinet", stateId: 1 },
        { name: "Grahamstown", stateId: 1 },
        { name: "King William’s Town", stateId: 1 },
        { name: "Mthatha", stateId: 1 },
        { name: "Port Elizabeth", stateId: 1 },
        { name: "Queenstown", stateId: 1 },
        { name: "Uitenhage", stateId: 1 },
        { name: "Zwelitsha", stateId: 1 },
        { name: "Bethlehem", stateId: 2 },
        { name: "Bloemfontein", stateId: 2 },
        { name: "Jagersfontein", stateId: 2 },
        { name: "Kroonstad", stateId: 2 },
        { name: "Odendaalsrus", stateId: 2 },
        { name: "Parys", stateId: 2 },
        { name: "Phuthaditjhaba", stateId: 2 },
        { name: "Sasolburg", stateId: 2 },
        { name: "Virginia", stateId: 2 },
        { name: "Welkom", stateId: 2 },
        { name: "Advertisement", stateId: 2 },
        { name: "Benoni", stateId: 3 },
        { name: "Boksburg", stateId: 3 },
        { name: "Brakpan", stateId: 3 },
        { name: "Carletonville", stateId: 3 },
        { name: "Germiston", stateId: 3 },
        { name: "Johannesburg", stateId: 3 },
        { name: "Krugersdorp", stateId: 3 },
        { name: "Pretoria", stateId: 3 },
        { name: "Randburg", stateId: 3 },
        { name: "Randfontein", stateId: 3 },
        { name: "Roodepoort", stateId: 3 },
        { name: "Soweto", stateId: 3 },
        { name: "Springs", stateId: 3 },
        { name: "Vanderbijlpark", stateId: 3 },
        { name: "Vereeniging", stateId: 3 },
        { name: "Durban", stateId: 4 },
        { name: "Empangeni", stateId: 4 },
        { name: "Ladysmith", stateId: 4 },
        { name: "Newcastle", stateId: 4 },
        { name: "Pietermaritzburg", stateId: 4 },
        { name: "Pinetown", stateId: 4 },
        { name: "Ulundi", stateId: 4 },
        { name: "Umlazi", stateId: 4 },
        { name: "Advertisement", stateId: 4 },
        { name: "Giyani", stateId: 5 },
        { name: "Lebowakgomo", stateId: 5 },
        { name: "Musina", stateId: 5 },
        { name: "Phalaborwa", stateId: 5 },
        { name: "Polokwane", stateId: 5 },
        { name: "Seshego", stateId: 5 },
        { name: "Sibasa", stateId: 5 },
        { name: "Thabazimbi", stateId: 5 },
        { name: "Emalahleni", stateId: 6 },
        { name: "Nelspruit", stateId: 6 },
        { name: "Secunda", stateId: 6 },
        { name: "Klerksdorp", stateId: 7 },
        { name: "Mahikeng", stateId: 7 },
        { name: "Mmabatho", stateId: 7 },
        { name: "Potchefstroom", stateId: 7 },
        { name: "Rustenburg", stateId: 7 },
        { name: "Kimberley", stateId: 8 },
        { name: "Kuruman", stateId: 8 },
        { name: "Port Nolloth", stateId: 8 },
        { name: "Bellville", stateId: 9 },
        { name: "Cape Town", stateId: 9 },
        { name: "Constantia", stateId: 9 },
        { name: "George", stateId: 9 },
        { name: "Hopefield", stateId: 9 },
        { name: "Oudtshoorn", stateId: 9 },
        { name: "Paarl", stateId: 9 },
        { name: "Simon’s Town", stateId: 9 },
        { name: "Stellenbosch", stateId: 9 },
        { name: "Swellendam", stateId: 9 },
        { name: "Worcester", stateId: 9 }
    ]));
}

function migrateSuburb() {
    return Suburb.sync({ force: true }).then(() => Suburb.bulkCreate([
        { name: "Carter", postalCode: 7884, cityId: 1 },
        { name: "Ritchie", postalCode: 7263, cityId: 2 },
        { name: "Nienow", postalCode: 4431, cityId: 3 },
        { name: "Fisher", postalCode: 1572, cityId: 4 },
        { name: "Leffler", postalCode: 2360, cityId: 5 },
        { name: "Hills", postalCode: 7608, cityId: 6 },
        { name: "Daniel", postalCode: 9083, cityId: 7 },
        { name: "Carter", postalCode: 1192, cityId: 8 },
        { name: "Carroll", postalCode: 2006, cityId: 9 },
        { name: "Haley", postalCode: 5147, cityId: 10 },
        { name: "Feest", postalCode: 4292, cityId: 11 },
        { name: "Cassin", postalCode: 9733, cityId: 12 },
        { name: "Jacobi", postalCode: 1395, cityId: 13 },
        { name: "Tromp", postalCode: 3410, cityId: 14 },
        { name: "Greenfelder", postalCode: 1963, cityId: 15 },
        { name: "Huel", postalCode: 5509, cityId: 16 },
        { name: "Kessler", postalCode: 6994, cityId: 17 },
        { name: "Lynch", postalCode: 4152, cityId: 18 },
        { name: "Koss", postalCode: 9541, cityId: 19 },
        { name: "Lakin", postalCode: 1048, cityId: 20 },
        { name: "Schultz", postalCode: 3599, cityId: 21 },
        { name: "Hilll", postalCode: 5470, cityId: 22 },
        { name: "Block", postalCode: 7912, cityId: 23 },
        { name: "Kohler", postalCode: 4565, cityId: 24 },
        { name: "Stoltenberg", postalCode: 3713, cityId: 25 },
        { name: "O'Keefe", postalCode: 6937, cityId: 26 },
        { name: "Schinner", postalCode: 6336, cityId: 27 },
        { name: "Kling", postalCode: 9140, cityId: 28 },
        { name: "Murphy", postalCode: 1910, cityId: 29 },
        { name: "Cruickshank", postalCode: 2460, cityId: 30 },
        { name: "Braun", postalCode: 6066, cityId: 31 },
        { name: "Kuphal", postalCode: 8540, cityId: 32 },
        { name: "Leffler", postalCode: 3494, cityId: 33 },
        { name: "Ziemann", postalCode: 6312, cityId: 34 },
        { name: "Olson", postalCode: 8367, cityId: 35 },
        { name: "Brekke", postalCode: 4947, cityId: 36 },
        { name: "Cormier", postalCode: 6985, cityId: 37 },
        { name: "Lowe", postalCode: 1564, cityId: 38 },
        { name: "Davis", postalCode: 9614, cityId: 39 },
        { name: "DuBuque", postalCode: 4679, cityId: 40 },
        { name: "Blick", postalCode: 7668, cityId: 41 },
        { name: "Abbott", postalCode: 7767, cityId: 42 },
        { name: "Mosciski", postalCode: 5062, cityId: 43 },
        { name: "Gerhold", postalCode: 6244, cityId: 44 },
        { name: "Kirlin", postalCode: 5480, cityId: 45 },
        { name: "Simonis", postalCode: 2526, cityId: 46 },
        { name: "Hayes", postalCode: 7917, cityId: 47 },
        { name: "Hermann", postalCode: 8747, cityId: 48 },
        { name: "Weber", postalCode: 8292, cityId: 49 },
        { name: "Adams", postalCode: 6008, cityId: 50 },
        { name: "Rutherford", postalCode: 3530, cityId: 51 },
        { name: "Pfannerstill", postalCode: 5060, cityId: 52 },
        { name: "Howell", postalCode: 7963, cityId: 53 },
        { name: "Sanford", postalCode: 2316, cityId: 54 },
        { name: "Aufderhar", postalCode: 5403, cityId: 55 },
        { name: "Howell", postalCode: 4715, cityId: 56 },
        { name: "Walker", postalCode: 2048, cityId: 57 },
        { name: "Boehm", postalCode: 1845, cityId: 58 },
        { name: "Douglas", postalCode: 5632, cityId: 59 },
        { name: "Hirthe", postalCode: 2556, cityId: 60 },
        { name: "Kris", postalCode: 9436, cityId: 61 },
        { name: "Tremblay", postalCode: 4317, cityId: 62 },
        { name: "Monahan", postalCode: 2672, cityId: 63 },
        { name: "Kutch", postalCode: 6377, cityId: 64 },
        { name: "Howell", postalCode: 9500, cityId: 65 },
        { name: "Gislason", postalCode: 7808, cityId: 66 },
        { name: "Bailey", postalCode: 9312, cityId: 67 },
        { name: "Muller", postalCode: 7105, cityId: 68 },
        { name: "Ankunding", postalCode: 7984, cityId: 69 },
        { name: "Cronin", postalCode: 1597, cityId: 70 },
        { name: "Keebler", postalCode: 3390, cityId: 71 },
        { name: "Pacocha", postalCode: 2980, cityId: 72 },
        { name: "Adams", postalCode: 7601, cityId: 73 },
        { name: "Mohr", postalCode: 5239, cityId: 74 },
        { name: "Ortiz", postalCode: 2907, cityId: 75 },
        { name: "Mraz", postalCode: 6733, cityId: 76 },
        { name: "Lynch", postalCode: 2957, cityId: 1 },
        { name: "Hickle", postalCode: 4247, cityId: 2 },
        { name: "Durgan", postalCode: 7395, cityId: 3 },
        { name: "Rau", postalCode: 5638, cityId: 4 },
        { name: "Krajcik", postalCode: 7982, cityId: 5 },
        { name: "Bartoletti", postalCode: 7492, cityId: 6 },
        { name: "Runolfsson", postalCode: 7047, cityId: 7 },
        { name: "Cronin", postalCode: 5062, cityId: 8 },
        { name: "Schneider", postalCode: 9777, cityId: 9 },
        { name: "Bauch", postalCode: 7201, cityId: 10 },
        { name: "Lang", postalCode: 6740, cityId: 11 },
        { name: "Schumm", postalCode: 3283, cityId: 12 },
        { name: "Lueilwitz", postalCode: 8851, cityId: 13 },
        { name: "Ankunding", postalCode: 4775, cityId: 14 },
        { name: "Cole", postalCode: 7202, cityId: 15 },
        { name: "Ebert", postalCode: 5420, cityId: 16 },
        { name: "Schmitt", postalCode: 8960, cityId: 17 },
        { name: "Torphy", postalCode: 3399, cityId: 18 },
        { name: "Robel", postalCode: 5380, cityId: 19 },
        { name: "Sauer", postalCode: 8015, cityId: 20 },
        { name: "Schaden", postalCode: 6118, cityId: 21 },
        { name: "Hahn", postalCode: 9062, cityId: 22 },
        { name: "Hintz", postalCode: 6348, cityId: 23 },
        { name: "Rogahn", postalCode: 9917, cityId: 24 },
        { name: "Kuhlman", postalCode: 1313, cityId: 25 },
        { name: "Zieme", postalCode: 7063, cityId: 26 },
        { name: "Crona", postalCode: 7325, cityId: 27 },
        { name: "Barrows", postalCode: 5499, cityId: 28 },
        { name: "Shanahan", postalCode: 7106, cityId: 29 },
        { name: "Borer", postalCode: 2178, cityId: 30 },
        { name: "Willms", postalCode: 1271, cityId: 31 },
        { name: "Bosco", postalCode: 8568, cityId: 32 },
        { name: "Kozey", postalCode: 5039, cityId: 33 },
        { name: "Wiza", postalCode: 5916, cityId: 34 },
        { name: "Sporer", postalCode: 1093, cityId: 35 },
        { name: "Ratke", postalCode: 5239, cityId: 36 },
        { name: "Witting", postalCode: 3915, cityId: 37 },
        { name: "Lind", postalCode: 3878, cityId: 38 },
        { name: "Walker", postalCode: 9886, cityId: 39 },
        { name: "Waters", postalCode: 9157, cityId: 40 },
        { name: "Herman", postalCode: 3525, cityId: 41 },
        { name: "Grimes", postalCode: 8489, cityId: 42 },
        { name: "Jast", postalCode: 4392, cityId: 43 },
        { name: "Balistreri", postalCode: 1867, cityId: 44 },
        { name: "Shanahan", postalCode: 6545, cityId: 45 },
        { name: "Nikolaus", postalCode: 4824, cityId: 46 },
        { name: "Beatty", postalCode: 6843, cityId: 47 },
        { name: "Upton", postalCode: 4413, cityId: 48 },
        { name: "Koelpin", postalCode: 2453, cityId: 49 },
        { name: "VonRueden", postalCode: 3452, cityId: 50 },
        { name: "Halvorson", postalCode: 5487, cityId: 51 },
        { name: "Carroll", postalCode: 7841, cityId: 52 },
        { name: "Fisher", postalCode: 3167, cityId: 53 },
        { name: "Bailey", postalCode: 2786, cityId: 54 },
        { name: "Buckridge", postalCode: 9923, cityId: 55 },
        { name: "Wintheiser", postalCode: 3359, cityId: 56 },
        { name: "Lind", postalCode: 2674, cityId: 57 },
        { name: "Baumbach", postalCode: 5181, cityId: 58 },
        { name: "Quigley", postalCode: 8532, cityId: 59 },
        { name: "Paucek", postalCode: 3566, cityId: 60 },
        { name: "Lesch", postalCode: 9996, cityId: 61 },
        { name: "Mosciski", postalCode: 8170, cityId: 62 },
        { name: "O'Connell", postalCode: 6093, cityId: 63 },
        { name: "Schmeler", postalCode: 7926, cityId: 64 },
        { name: "Hagenes", postalCode: 3329, cityId: 65 },
        { name: "Dicki", postalCode: 2035, cityId: 66 },
        { name: "Purdy", postalCode: 1202, cityId: 67 },
        { name: "Schulist", postalCode: 3496, cityId: 68 },
        { name: "Luettgen", postalCode: 5996, cityId: 69 },
        { name: "Graham", postalCode: 1944, cityId: 70 },
        { name: "Moen", postalCode: 9341, cityId: 71 },
        { name: "Bashirian", postalCode: 4185, cityId: 72 },
        { name: "Huel", postalCode: 5398, cityId: 73 },
        { name: "Feeney", postalCode: 2864, cityId: 74 },
        { name: "Veum", postalCode: 6829, cityId: 75 },
        { name: "Mitchell", postalCode: 6745, cityId: 76 },
        { name: "Lynch", postalCode: 6712, cityId: 1 },
        { name: "Koepp", postalCode: 2271, cityId: 2 },
        { name: "Crona", postalCode: 8655, cityId: 3 },
        { name: "Pouros", postalCode: 9001, cityId: 4 },
        { name: "Kemmer", postalCode: 7641, cityId: 5 },
        { name: "Swaniawski", postalCode: 9941, cityId: 6 },
        { name: "Jacobi", postalCode: 2549, cityId: 7 },
        { name: "Konopelski", postalCode: 4490, cityId: 8 },
        { name: "Gleichner", postalCode: 7047, cityId: 9 },
        { name: "Armstrong", postalCode: 2345, cityId: 10 },
        { name: "Jakubowski", postalCode: 6722, cityId: 11 },
        { name: "Russel", postalCode: 7529, cityId: 12 },
        { name: "Mante", postalCode: 2528, cityId: 13 },
        { name: "Cormier", postalCode: 1266, cityId: 14 },
        { name: "Dibbert", postalCode: 6430, cityId: 15 },
        { name: "Macejkovic", postalCode: 8130, cityId: 16 },
        { name: "Hickle", postalCode: 2847, cityId: 17 },
        { name: "Sporer", postalCode: 7829, cityId: 18 },
        { name: "Kovacek", postalCode: 6033, cityId: 19 },
        { name: "Daniel", postalCode: 5682, cityId: 20 },
        { name: "Kreiger", postalCode: 8704, cityId: 21 },
        { name: "Grimes", postalCode: 7239, cityId: 22 },
        { name: "Stanton", postalCode: 1081, cityId: 23 },
        { name: "King", postalCode: 5820, cityId: 24 },
        { name: "Kohler", postalCode: 6130, cityId: 25 },
        { name: "Harris", postalCode: 8651, cityId: 26 },
        { name: "Metz", postalCode: 1400, cityId: 27 },
        { name: "Eichmann", postalCode: 4893, cityId: 28 },
        { name: "O'Hara", postalCode: 5791, cityId: 29 },
        { name: "Jerde", postalCode: 6092, cityId: 30 },
        { name: "Bogisich", postalCode: 6667, cityId: 31 },
        { name: "Stoltenberg", postalCode: 8373, cityId: 32 },
        { name: "Dibbert", postalCode: 5194, cityId: 33 },
        { name: "Lubowitz", postalCode: 1333, cityId: 34 },
        { name: "Zulauf", postalCode: 3759, cityId: 35 },
        { name: "Rice", postalCode: 1049, cityId: 36 },
        { name: "Gislason", postalCode: 8869, cityId: 37 },
        { name: "Crooks", postalCode: 4529, cityId: 38 },
        { name: "Runte", postalCode: 8820, cityId: 39 },
        { name: "Ernser", postalCode: 2809, cityId: 40 },
        { name: "Cartwright", postalCode: 5626, cityId: 41 },
        { name: "Prosacco", postalCode: 6705, cityId: 42 },
        { name: "Mosciski", postalCode: 7360, cityId: 43 },
        { name: "Abbott", postalCode: 1835, cityId: 44 },
        { name: "Hayes", postalCode: 3318, cityId: 45 },
        { name: "Hickle", postalCode: 6113, cityId: 46 },
        { name: "McKenzie", postalCode: 2524, cityId: 47 },
        { name: "Feeney", postalCode: 5207, cityId: 48 },
        { name: "Waelchi", postalCode: 1550, cityId: 49 },
        { name: "Kreiger", postalCode: 5047, cityId: 50 },
        { name: "Lubowitz", postalCode: 1276, cityId: 51 },
        { name: "Reichert", postalCode: 3258, cityId: 52 },
        { name: "Beer", postalCode: 2230, cityId: 53 },
        { name: "Luettgen", postalCode: 8605, cityId: 54 },
        { name: "Wehner", postalCode: 2880, cityId: 55 },
        { name: "Brekke", postalCode: 2770, cityId: 56 },
        { name: "Reichel", postalCode: 8830, cityId: 57 },
        { name: "Bahringer", postalCode: 7570, cityId: 58 },
        { name: "Gottlieb", postalCode: 3452, cityId: 59 },
        { name: "Larkin", postalCode: 7780, cityId: 60 },
        { name: "Schaefer", postalCode: 6574, cityId: 61 },
        { name: "Heaney", postalCode: 9299, cityId: 62 },
        { name: "Turcotte", postalCode: 6222, cityId: 63 },
        { name: "Deckow", postalCode: 2628, cityId: 64 },
        { name: "Hodkiewicz", postalCode: 9361, cityId: 65 },
        { name: "Douglas", postalCode: 8363, cityId: 66 },
        { name: "Botsford", postalCode: 6439, cityId: 67 },
        { name: "Vandervort", postalCode: 6813, cityId: 68 },
        { name: "Brekke", postalCode: 8687, cityId: 69 },
        { name: "Harris", postalCode: 6146, cityId: 70 },
        { name: "Bergstrom", postalCode: 7256, cityId: 71 },
        { name: "Olson", postalCode: 9219, cityId: 72 },
        { name: "Willms", postalCode: 9786, cityId: 73 },
        { name: "Collier", postalCode: 2473, cityId: 74 },
        { name: "Lynch", postalCode: 9133, cityId: 75 },
        { name: "Koepp", postalCode: 9683, cityId: 7 }
    ]));
}

function migrateBaseAddress() {
    return BaseAddress.sync({ force: true }).then(() => BaseAddress.bulkCreate([
        { addressLine1: "55403 Purdy Greens", addressLine2: "3337 Chaz Ramp", suburbId: 1 },
        { addressLine1: "3028 Schinner Run Suite 299", addressLine2: "7619 Deborah Junction Suite 001", suburbId: 2 },
        { addressLine1: "87660 Bailey Garden", addressLine2: "938 Metz Oval", suburbId: 3 },
        { addressLine1: "8790 Ferry Crossroad", addressLine2: "366 Guadalupe Landing", suburbId: 4 },
        { addressLine1: "745 Cassin Islands", addressLine2: "052 Koelpin Plains", suburbId: 5 },
        { addressLine1: "340 Afton View", addressLine2: "2925 Skiles Plaza", suburbId: 6 },
        { addressLine1: "77916 Hackett Landing Suite 504", addressLine2: "28179 Thompson Square Apt. 978", suburbId: 7 },
        { addressLine1: "2873 Dietrich Union", addressLine2: "58812 Lind Lock Suite 494", suburbId: 8 },
        { addressLine1: "82618 Xander Brook Suite 704", addressLine2: "676 Miller Meadows Apt. 376", suburbId: 9 },
        { addressLine1: "29438 Rolfson Avenue Apt. 746", addressLine2: "4416 Sibyl Fort Apt. 156", suburbId: 10 },
        { addressLine1: "9030 Harmon Creek Apt. 306", addressLine2: "3430 Koepp Corner Apt. 391", suburbId: 11 },
        { addressLine1: "208 Doyle Streets", addressLine2: "6286 Zachery Streets Apt. 589", suburbId: 12 },
        { addressLine1: "5504 Maggio Glens Suite 191", addressLine2: "60810 Walsh Track Suite 457", suburbId: 13 },
        { addressLine1: "2418 Wisoky Route", addressLine2: "08203 Rau Keys", suburbId: 14 },
        { addressLine1: "959 Maverick Run", addressLine2: "9890 Herman Throughway Suite 237", suburbId: 15 },
        { addressLine1: "708 Lyla Flats Suite 812", addressLine2: "9625 Barrows Valleys", suburbId: 16 },
        { addressLine1: "862 Ned Pass", addressLine2: "981 Beahan Causeway Apt. 418", suburbId: 17 },
        { addressLine1: "1993 Ludwig Via Suite 521", addressLine2: "659 Schaefer Square Suite 850", suburbId: 18 },
        { addressLine1: "131 Shany Streets", addressLine2: "87979 Geraldine Orchard Apt. 336", suburbId: 19 },
        { addressLine1: "2264 Camron Lake", addressLine2: "5263 Joanie Port Apt. 758", suburbId: 20 },
        { addressLine1: "782 Bennie Course Apt. 333", addressLine2: "292 Wehner Key Suite 147", suburbId: 21 },
        { addressLine1: "98597 Angeline Curve", addressLine2: "2039 Gleichner Forest Suite 874", suburbId: 22 },
        { addressLine1: "560 Tina Center Suite 774", addressLine2: "957 Alexandre Glens Apt. 697", suburbId: 23 },
        { addressLine1: "945 Rowe Center Apt. 903", addressLine2: "014 Berge Fall", suburbId: 24 },
        { addressLine1: "563 Armstrong Falls Suite 845", addressLine2: "106 Scotty Mission", suburbId: 25 },
        { addressLine1: "4791 Leann Parkway", addressLine2: "636 Gavin Estate Suite 025", suburbId: 26 },
        { addressLine1: "9366 Bechtelar Street", addressLine2: "53974 Kaylah Row", suburbId: 27 },
        { addressLine1: "602 Watson Plaza Apt. 840", addressLine2: "580 Amiya Extensions Suite 904", suburbId: 28 },
        { addressLine1: "1376 Brett Knoll", addressLine2: "923 Stoltenberg Roads Apt. 122", suburbId: 29 },
        { addressLine1: "8703 Deontae Park Apt. 972", addressLine2: "965 Emmerich Vista Apt. 240", suburbId: 30 },
        { addressLine1: "3649 Santos Station", addressLine2: "67589 Myrtis Passage", suburbId: 31 },
        { addressLine1: "110 Ardith Center Apt. 005", addressLine2: "277 Ramon Fork Apt. 336", suburbId: 32 },
        { addressLine1: "6657 Deondre Rest Suite 876", addressLine2: "647 Mervin Turnpike", suburbId: 33 },
        { addressLine1: "27238 Demetrius Union", addressLine2: "165 Unique Place", suburbId: 34 },
        { addressLine1: "6970 Hessel Hills Suite 509", addressLine2: "5211 Sipes Expressway", suburbId: 35 },
        { addressLine1: "564 Boyd Shoal", addressLine2: "9190 Haley Field Apt. 985", suburbId: 36 },
        { addressLine1: "9087 Gaylord Place Apt. 360", addressLine2: "354 Leora Oval", suburbId: 37 },
        { addressLine1: "2337 Alycia Causeway", addressLine2: "37779 Eriberto Grove Suite 176", suburbId: 38 },
        { addressLine1: "073 Green Keys", addressLine2: "87310 Mayer Island Suite 770", suburbId: 39 },
        { addressLine1: "7521 Luciano Pines Apt. 612", addressLine2: "733 Natasha Ridge", suburbId: 40 },
        { addressLine1: "151 Mikel Manor Suite 724", addressLine2: "517 Christy Fork", suburbId: 41 },
        { addressLine1: "6786 Robel Island Suite 770", addressLine2: "100 Adaline Heights", suburbId: 42 },
        { addressLine1: "389 Pfeffer Ford", addressLine2: "499 Leuschke Club Apt. 293", suburbId: 43 },
        { addressLine1: "780 Norbert Falls Suite 327", addressLine2: "761 Dorian Trafficway Suite 791", suburbId: 44 },
        { addressLine1: "082 Scarlett Ferry Apt. 374", addressLine2: "0303 Sipes Tunnel Suite 315", suburbId: 45 },
        { addressLine1: "952 Williamson Roads", addressLine2: "5605 Hahn Extensions Suite 781", suburbId: 46 },
        { addressLine1: "647 Toney River Suite 426", addressLine2: "486 Wiegand Stravenue", suburbId: 47 },
        { addressLine1: "24534 Tyrique Valley", addressLine2: "9072 Herbert Springs Suite 663", suburbId: 48 },
        { addressLine1: "912 Legros Oval", addressLine2: "496 Fahey Groves Apt. 315", suburbId: 49 },
        { addressLine1: "784 Krista Village", addressLine2: "821 Carter Curve Apt. 020", suburbId: 50 },
        { addressLine1: "5793 Blaise Spurs", addressLine2: "161 Elody Garden Apt. 914", suburbId: 51 },
        { addressLine1: "723 Wilma Mission", addressLine2: "665 Pinkie Trail Apt. 932", suburbId: 52 },
        { addressLine1: "70832 Schoen Square", addressLine2: "49541 Alexane Meadows Apt. 130", suburbId: 53 },
        { addressLine1: "62267 Deshawn Pines", addressLine2: "0926 Dimitri Course Suite 028", suburbId: 54 },
        { addressLine1: "0111 Champlin Viaduct Suite 565", addressLine2: "1207 Ross Lane Suite 106", suburbId: 55 },
        { addressLine1: "85662 Kshlerin Vista", addressLine2: "37902 Marvin Station Apt. 324", suburbId: 56 },
        { addressLine1: "10718 Caleigh Trafficway", addressLine2: "2541 Wisoky Curve", suburbId: 57 },
        { addressLine1: "367 Angelita Bypass Suite 953", addressLine2: "7970 Malinda Brooks Suite 638", suburbId: 58 },
        { addressLine1: "99398 Antonina Greens", addressLine2: "135 Cleora Way", suburbId: 59 },
        { addressLine1: "81327 Milo Lodge Apt. 630", addressLine2: "1009 Orn Squares", suburbId: 60 },
        { addressLine1: "547 Theresia Inlet", addressLine2: "5132 Jose Skyway Apt. 885", suburbId: 61 },
        { addressLine1: "0052 Emory Curve", addressLine2: "488 Emily Branch Suite 174", suburbId: 62 },
        { addressLine1: "68816 Madie Turnpike", addressLine2: "308 Rosamond Shores Apt. 305", suburbId: 63 },
        { addressLine1: "095 Ledner Valleys Suite 780", addressLine2: "51922 Lina Ramp", suburbId: 64 },
        { addressLine1: "11063 Gleason Wells Apt. 024", addressLine2: "70002 Mills Tunnel Suite 921", suburbId: 65 },
        { addressLine1: "9787 Ezequiel Burgs", addressLine2: "2167 Candace Rue", suburbId: 66 },
        { addressLine1: "07592 Estrella Road", addressLine2: "57804 Robbie Knoll Apt. 671", suburbId: 67 },
        { addressLine1: "67342 Bo Crossing", addressLine2: "66203 Catherine Extensions", suburbId: 68 },
        { addressLine1: "58823 Ziemann Locks Apt. 102", addressLine2: "54960 Feil Loaf", suburbId: 69 },
        { addressLine1: "2094 Okuneva Terrace", addressLine2: "65363 Marlen Rapid Suite 181", suburbId: 70 },
        { addressLine1: "8951 Heller Crossroad", addressLine2: "1281 Reichel Walks Suite 742", suburbId: 71 },
        { addressLine1: "03846 Orland Bridge", addressLine2: "215 Margot Parkway Suite 633", suburbId: 72 },
        { addressLine1: "11396 Connie Mountain", addressLine2: "44900 Dicki Stravenue Apt. 433", suburbId: 73 },
        { addressLine1: "06443 Erich Inlet", addressLine2: "30975 Richmond Lake Suite 20", suburbId: 74 },
        { addressLine1: "234 Anabelle Keys Suite 141", addressLine2: "", suburbId: 75 },
        { addressLine1: "4827 Fadel Park Suite 443", addressLine2: "", suburbId: 76 },
        { addressLine1: "8371 Gwendolyn River Suite 617", addressLine2: "", suburbId: 77 },
        { addressLine1: "14959 Walter Circle Apt. 552", addressLine2: "", suburbId: 78 },
        { addressLine1: "452 Frankie Plaza", addressLine2: "", suburbId: 79 },
        { addressLine1: "1591 Crooks Shore Apt. 684", addressLine2: "", suburbId: 80 },
        { addressLine1: "4863 Amaya Shores Suite 126", addressLine2: "", suburbId: 81 },
        { addressLine1: "7948 Durgan Ferry", addressLine2: "", suburbId: 82 },
        { addressLine1: "4743 Unique Brooks", addressLine2: "", suburbId: 83 },
        { addressLine1: "213 Heathcote Cliff Apt. 286", addressLine2: "", suburbId: 84 },
        { addressLine1: "201 Verner Mills Suite 327", addressLine2: "", suburbId: 85 },
        { addressLine1: "8360 Ethan Tunnel Apt. 782", addressLine2: "", suburbId: 86 },
        { addressLine1: "13586 Walker Stream", addressLine2: "", suburbId: 87 },
        { addressLine1: "78581 Aidan Creek", addressLine2: "", suburbId: 88 },
        { addressLine1: "073 Sylvester Loop Suite 687", addressLine2: "", suburbId: 89 },
        { addressLine1: "261 Triston Coves", addressLine2: "", suburbId: 90 },
        { addressLine1: "0338 Judd Pines", addressLine2: "", suburbId: 91 },
        { addressLine1: "270 Ransom Meadows Suite 850", addressLine2: "", suburbId: 92 },
        { addressLine1: "898 Kovacek Ramp", addressLine2: "", suburbId: 93 },
        { addressLine1: "37118 Rosendo Square Apt. 859", addressLine2: "", suburbId: 94 },
        { addressLine1: "792 Bartell Viaduct", addressLine2: "", suburbId: 95 },
        { addressLine1: "48102 Keeley Burg Apt. 323", addressLine2: "", suburbId: 96 },
        { addressLine1: "71650 Bosco Passage Apt. 257", addressLine2: "", suburbId: 97 },
        { addressLine1: "5335 Makayla Stravenue", addressLine2: "", suburbId: 98 },
        { addressLine1: "72912 Margret Manor", addressLine2: "", suburbId: 99 },
        { addressLine1: "54846 Johnson Way", addressLine2: "", suburbId: 100 },
        { addressLine1: "Monserrat Crescent", addressLine2: "", suburbId: 101 },
        { addressLine1: "Nicole Road", addressLine2: "", suburbId: 102 },
        { addressLine1: "Paula Lane", addressLine2: "", suburbId: 103 },
        { addressLine1: "Leopoldo Place", addressLine2: "", suburbId: 104 },
        { addressLine1: "Chanelle Street", addressLine2: "", suburbId: 105 },
        { addressLine1: "Joesph Avenue", addressLine2: "", suburbId: 106 },
        { addressLine1: "Mario Crescent", addressLine2: "", suburbId: 107 },
        { addressLine1: "Meghan Road", addressLine2: "", suburbId: 108 },
        { addressLine1: "Chelsie Lane", addressLine2: "", suburbId: 109 },
        { addressLine1: "Edgardo Place", addressLine2: "", suburbId: 110 },
        { addressLine1: "Kelvin Street", addressLine2: "", suburbId: 111 },
        { addressLine1: "Leonora Avenue", addressLine2: "", suburbId: 112 },
        { addressLine1: "Daphne Street", addressLine2: "", suburbId: 113 },
        { addressLine1: "Darrel Avenue", addressLine2: "", suburbId: 114 },
        { addressLine1: "Demarcus Crescent", addressLine2: "", suburbId: 115 },
        { addressLine1: "Gracie Road", addressLine2: "", suburbId: 116 },
        { addressLine1: "Micheal Lane", addressLine2: "", suburbId: 117 },
        { addressLine1: "Eugenia Place", addressLine2: "", suburbId: 118 },
        { addressLine1: "Erin Street", addressLine2: "", suburbId: 119 },
        { addressLine1: "Jaylon Avenue", addressLine2: "", suburbId: 120 },
        { addressLine1: "Kathleen Crescent", addressLine2: "", suburbId: 121 },
        { addressLine1: "Zachery Road", addressLine2: "", suburbId: 122 },
        { addressLine1: "Mireille Lane", addressLine2: "", suburbId: 123 },
        { addressLine1: "Mossie Place", addressLine2: "", suburbId: 124 },
        { addressLine1: "Kayla Street", addressLine2: "", suburbId: 125 },
        { addressLine1: "Brock Avenue", addressLine2: "", suburbId: 126 },
        { addressLine1: "Chelsey Street", addressLine2: "", suburbId: 127 },
        { addressLine1: "Freda Avenue", addressLine2: "", suburbId: 128 },
        { addressLine1: "Ari Crescent", addressLine2: "", suburbId: 129 },
        { addressLine1: "Selina Road", addressLine2: "", suburbId: 130 },
        { addressLine1: "Anika Lane", addressLine2: "", suburbId: 131 },
        { addressLine1: "Ryleigh Place", addressLine2: "", suburbId: 132 },
        { addressLine1: "Claude Street", addressLine2: "", suburbId: 133 },
        { addressLine1: "Jett Avenue", addressLine2: "", suburbId: 134 },
        { addressLine1: "Gino Crescent", addressLine2: "", suburbId: 135 },
        { addressLine1: "Darius Road", addressLine2: "", suburbId: 136 },
        { addressLine1: "Elaina Lane", addressLine2: "", suburbId: 137 },
        { addressLine1: "Lucinda Place", addressLine2: "", suburbId: 138 },
        { addressLine1: "Catalina Street", addressLine2: "", suburbId: 139 },
        { addressLine1: "Marquise Avenue", addressLine2: "", suburbId: 140 },
        { addressLine1: "Estella Street", addressLine2: "", suburbId: 141 },
        { addressLine1: "Mustafa Avenue", addressLine2: "", suburbId: 142 },
        { addressLine1: "Kevin Crescent", addressLine2: "", suburbId: 143 },
        { addressLine1: "Kaycee Road", addressLine2: "", suburbId: 144 },
        { addressLine1: "Abagail Lane", addressLine2: "", suburbId: 145 },
        { addressLine1: "Craig Place", addressLine2: "", suburbId: 146 },
        { addressLine1: "Stuart Street", addressLine2: "", suburbId: 147 },
        { addressLine1: "Scarlett Avenue", addressLine2: "", suburbId: 148 },
        { addressLine1: "Reba Crescent", addressLine2: "", suburbId: 149 },
        { addressLine1: "Kaylee Road", addressLine2: "", suburbId: 150 },
        { addressLine1: "Zola Lane", addressLine2: "", suburbId: 151 },
        { addressLine1: "Scarlett Place", addressLine2: "", suburbId: 152 },
        { addressLine1: "Arlie Street", addressLine2: "", suburbId: 153 },
        { addressLine1: "Casimer Avenue", addressLine2: "", suburbId: 154 },
        { addressLine1: "Milton Street", addressLine2: "", suburbId: 155 },
        { addressLine1: "Jovany Avenue", addressLine2: "", suburbId: 156 },
        { addressLine1: "Tyler Crescent", addressLine2: "", suburbId: 157 },
        { addressLine1: "Rico Road", addressLine2: "", suburbId: 158 },
        { addressLine1: "Retha Lane", addressLine2: "", suburbId: 159 },
        { addressLine1: "Tyra Place", addressLine2: "", suburbId: 160 },
        { addressLine1: "Kristian Street", addressLine2: "", suburbId: 161 },
        { addressLine1: "Kellen Avenue", addressLine2: "", suburbId: 162 },
        { addressLine1: "Stephon Crescent", addressLine2: "", suburbId: 163 },
        { addressLine1: "Sonia Road", addressLine2: "", suburbId: 164 },
        { addressLine1: "Marian Lane", addressLine2: "", suburbId: 165 },
        { addressLine1: "Josie Place", addressLine2: "", suburbId: 166 },
        { addressLine1: "Karen Street", addressLine2: "", suburbId: 167 },
        { addressLine1: "Breanne Avenue", addressLine2: "", suburbId: 168 },
        { addressLine1: "Myriam Street", addressLine2: "", suburbId: 169 },
        { addressLine1: "Skye Avenue", addressLine2: "", suburbId: 170 },
        { addressLine1: "Alena Crescent", addressLine2: "", suburbId: 171 },
        { addressLine1: "Nikita Road", addressLine2: "", suburbId: 172 },
        { addressLine1: "Savanah Lane", addressLine2: "", suburbId: 173 },
        { addressLine1: "Mozelle Place", addressLine2: "", suburbId: 174 },
        { addressLine1: "Garnet Street", addressLine2: "", suburbId: 175 },
        { addressLine1: "Everette Avenue", addressLine2: "", suburbId: 176 },
        { addressLine1: "Elroy Crescent", addressLine2: "", suburbId: 177 },
        { addressLine1: "Linnie Road", addressLine2: "", suburbId: 178 },
        { addressLine1: "Franz Lane", addressLine2: "", suburbId: 179 },
        { addressLine1: "Freddie Place", addressLine2: "", suburbId: 180 },
        { addressLine1: "Orlando Street", addressLine2: "", suburbId: 181 },
        { addressLine1: "David Avenue", addressLine2: "", suburbId: 182 },
        { addressLine1: "Ferne Street", addressLine2: "", suburbId: 183 },
        { addressLine1: "Thelma Avenue", addressLine2: "", suburbId: 184 },
        { addressLine1: "Jon Crescent", addressLine2: "", suburbId: 185 },
        { addressLine1: "Freida Road", addressLine2: "", suburbId: 186 },
        { addressLine1: "Marielle Lane", addressLine2: "", suburbId: 187 },
        { addressLine1: "Della Place", addressLine2: "", suburbId: 188 },
        { addressLine1: "Candice Street", addressLine2: "", suburbId: 189 },
        { addressLine1: "Griffin Avenue", addressLine2: "", suburbId: 190 },
        { addressLine1: "Rusty Crescent", addressLine2: "", suburbId: 191 },
        { addressLine1: "Barrett Road", addressLine2: "", suburbId: 192 },
        { addressLine1: "Shaniya Lane", addressLine2: "", suburbId: 193 },
        { addressLine1: "Jasmin Place", addressLine2: "", suburbId: 194 },
        { addressLine1: "Casimer Street", addressLine2: "", suburbId: 195 },
        { addressLine1: "Jeramie Avenue", addressLine2: "", suburbId: 196 },
        { addressLine1: "Lesley Street", addressLine2: "", suburbId: 197 },
        { addressLine1: "Patience Avenue", addressLine2: "", suburbId: 198 },
        { addressLine1: "Willard Crescent", addressLine2: "", suburbId: 199 },
        { addressLine1: "Althea Road", addressLine2: "", suburbId: 200 },
        { addressLine1: "Henri Lane", addressLine2: "", suburbId: 201 },
        { addressLine1: "Julia Place", addressLine2: "", suburbId: 202 },
        { addressLine1: "Gerry Street", addressLine2: "", suburbId: 203 },
        { addressLine1: "Gillian Avenue", addressLine2: "", suburbId: 204 },
        { addressLine1: "Kayley Crescent", addressLine2: "", suburbId: 205 },
        { addressLine1: "Ali Road", addressLine2: "", suburbId: 206 },
        { addressLine1: "Hailie Lane", addressLine2: "", suburbId: 207 },
        { addressLine1: "Jerod Place", addressLine2: "", suburbId: 208 },
        { addressLine1: "Elinor Street", addressLine2: "", suburbId: 209 },
        { addressLine1: "Grady Avenue", addressLine2: "", suburbId: 210 },
        { addressLine1: "Larue Street", addressLine2: "", suburbId: 211 },
        { addressLine1: "Abbigail Avenue", addressLine2: "", suburbId: 212 },
        { addressLine1: "Cicero Crescent", addressLine2: "", suburbId: 213 },
        { addressLine1: "Palma Road", addressLine2: "", suburbId: 214 },
        { addressLine1: "Mylene Lane", addressLine2: "", suburbId: 215 },
        { addressLine1: "Jazmin Place", addressLine2: "", suburbId: 216 },
        { addressLine1: "Carlo Street", addressLine2: "", suburbId: 217 },
        { addressLine1: "Edythe Avenue", addressLine2: "", suburbId: 218 },
        { addressLine1: "Jarret Crescent", addressLine2: "", suburbId: 219 },
        { addressLine1: "Winfield Road", addressLine2: "", suburbId: 220 },
        { addressLine1: "Amos Lane", addressLine2: "", suburbId: 221 },
        { addressLine1: "Hayden Place", addressLine2: "", suburbId: 222 },
        { addressLine1: "Dee Street", addressLine2: "", suburbId: 223 },
        { addressLine1: "Vivien Avenue", addressLine2: "", suburbId: 224 },
        { addressLine1: "King Street", addressLine2: "", suburbId: 225 },
        { addressLine1: "Amiya Avenue", addressLine2: "", suburbId: 226 },
        { addressLine1: "Larissa Crescent", addressLine2: "", suburbId: 227 },
        { addressLine1: "Charles Road", addressLine2: "", suburbId: 228 },
        { addressLine1: "Lacey Avenue", addressLine2: "", suburbId: 1 },
        { addressLine1: "Maya Road", addressLine2: "", suburbId: 2 }
    ]));
}

function migrateApartmentAddress() {
    return ApartmentAddress.sync({ force: true }).then(() => ApartmentAddress.bulkCreate([
        { baseAddressId: 21, room: 21, floor: 9, building: "Bailey Building" },
        { baseAddressId: 22, room: 32, floor: 1, building: "Reichert Building" },
        { baseAddressId: 23, room: 23, floor: 7, building: "Stroman Building" },
        { baseAddressId: 24, room: 36, floor: 2, building: "Hettinger Building" },
        { baseAddressId: 25, room: 21, floor: 6, building: "Mosciski Building" },
        { baseAddressId: 26, room: 44, floor: 6, building: "Romaguera Apartments" },
        { baseAddressId: 27, room: 10, floor: 2, building: "Cummings Grove" },
        { baseAddressId: 28, room: 42, floor: 4, building: "Sporer Apartments" },
        { baseAddressId: 29, room: 35, floor: 7, building: "Hessel Building" },
        { baseAddressId: 30, room: 21, floor: 3, building: "Gerhold Apartments" },
        { baseAddressId: 31, room: 30, floor: 5, building: "Zemlak Grove" },
        { baseAddressId: 32, room: 29, floor: 2, building: "Mosciski Apartments" },
        { baseAddressId: 33, room: 2, floor: 8, building: "Klein Apartments" },
        { baseAddressId: 34, room: 19, floor: 5, building: "Gulgowski Apartments" },
        { baseAddressId: 35, room: 14, floor: 6, building: "Medhurst Apartments" },
        { baseAddressId: 36, room: 6, floor: 9, building: "Witting Grove" },
        { baseAddressId: 37, room: 40, floor: 5, building: "Pouros Apartments" },
        { baseAddressId: 38, room: 12, floor: 7, building: "Parker Grove Apartments" },
        { baseAddressId: 38, room: 13, floor: 7, building: "Parker Grove Apartments" },
        { baseAddressId: 38, room: 14, floor: 7, building: "Parker Grove Apartments" }
    ]));
}


function migrateBusinessAddress() {
    return BusinessAddress.sync({ force: true }).then(() => BusinessAddress.bulkCreate([
        { baseAddressId: 41, businessName: "Hilpert-West", description: "Facetoface analyzing service-desk", floor: 1, building: "MediumAquaMarine Grove", campus: "Kilback Campus" },
        { baseAddressId: 42, businessName: "Herzog-Heidenreich", description: "Networked high-level time-frame", floor: 7, building: "Magenta Square", campus: "Bode Campus" },
        { baseAddressId: 43, businessName: "Boyer, Mann and Adams", description: "Automated explicit collaboration", floor: 2, building: "MediumOrchid Gardens", campus: "Thompson Campus" },
        { baseAddressId: 44, businessName: "Gutmann PLC", description: "Multi-tiered bottom-line moderator", floor: 6, building: "Salmon Mews", campus: "Schinner Offices" },
        { baseAddressId: 45, businessName: "Runolfsdottir Ltd", description: "Re-engineered dedicated utilisation", floor: 9, building: "MediumSeaGreen Vale", campus: "Ortiz Group" },
        { baseAddressId: 46, businessName: "Schimmel-Streich Group", description: "Diverse client-server groupware", floor: 5, building: "Red Place", campus: "Turner Offices" },
        { baseAddressId: 46, businessName: "Runte-Reichert Ltd", description: "Mandatory actuating hierarchy", floor: 1, building: "Red Place", campus: "Turner Offices" },
        { baseAddressId: 46, businessName: "Koelpin Inc", description: "Profit-focused hybrid model", floor: 2, building: "Red Place", campus: "Turner Offices" },
        { baseAddressId: 46, businessName: "Steuber-Davis PLC", description: "Grass-roots object-oriented processimprovement", floor: 5, building: "Red Place", campus: "Turner Offices" },
        { baseAddressId: 46, businessName: "Fritsch, Hyatt and Jenkins Inc", description: "Re-contextualized 24hour hardware", floor: 9, building: "Red Place", campus: "Turner Offices" },
        { baseAddressId: 46, businessName: "Corwin-Murray Ltd", description: "De-engineered mission-critical intranet", floor: 1, building: "Red Place", campus: "Turner Offices" },
        { baseAddressId: 46, businessName: "Kuphal PLC", description: "Synchronised global hardware", floor: 1, building: "Crimson Place", campus: "Turner Offices" },
        { baseAddressId: 46, businessName: "Kutch-Krajcik Ltd", description: "Exclusive interactive adapter", floor: 9, building: "LightGoldenRodYellow Grove", campus: "Turner Offices" },
        { baseAddressId: 54, businessName: "Harvey-Bogisich LLC", description: "Synergized needs-based neural-net", floor: 4, building: "DarkTurquoise Square", campus: "Hahn Campus" },
        { baseAddressId: 55, businessName: "Gleichner, Bednar and Feeney LLC", description: "Phased web-enabled matrices", floor: 7, building: "Black Gardens", campus: "Pacocha Campus" },
        { baseAddressId: 56, businessName: "Emmerich-White PLC", description: "Fundamental foreground array", floor: 8, building: "SlateBlue Mews", campus: "Pacocha Campus" },
        { baseAddressId: 57, businessName: "Kilback, Dibbert, Hartmann and Sons", description: "Phased logistical access" },
        { baseAddressId: 58, businessName: "Lockman, Ernser and Kunze Group", description: "Decentralized zerotolerance array" },
        { baseAddressId: 59, businessName: "Waters, Hessel and Cronin Ltd", description: "Sharable 3rdgeneration projection" },
        { baseAddressId: 60, businessName: "Bechtelar, Daugherty and Jerde PLC", description: "Compatible background workforce", floor: 6, building: "PeachPuff Square", campus: "Hilpert Campus" },
        { baseAddressId: 60, businessName: "Watsica, Moore and Gerlach Inc", description: "Vision-oriented asynchronous artificialintelligence", floor: 5, building: "PeachPuff Square", campus: "Farrell Campus" },
        { baseAddressId: 60, businessName: "Runte-Stoltenberg and Sons", description: "Down-sized stable throughput", floor: 9, building: "PeachPuff Square", campus: "Heidenreich Campus" },
        { baseAddressId: 55, businessName: "Predovic Group", description: "Assimilated directional website", floor: 1, building: "Black Gardens" },
        { baseAddressId: 41, businessName: "Armstrong Inc", description: "Visionary even-keeled algorithm", floor: 2, building: "MediumAquaMarine Grove" },
        { baseAddressId: 42, businessName: "Sanford, Konopelski and Wiza PLC", description: "Re-contextualized object-oriented portal", floor: 5, building: "Magenta Square" },
        { baseAddressId: 43, businessName: "Reichert, Lubowitz and Block", description: "Stand-alone stable leverage", floor: 1, building: "MediumOrchid Gardens" },
        { baseAddressId: 44, businessName: "Bruen PLC", description: "Monitored multi-tasking adapter", floor: 6, building: "Salmon Mews" },
        { baseAddressId: 45, businessName: "Upton LLC", description: "Integrated mobile infrastructure", floor: 2, building: "MediumSeaGreen Vale" },
        { baseAddressId: 55, businessName: "Mann Ltd", description: "Quality-focused transitional encoding", floor: 7, building: "Black Gardens" },
        { baseAddressId: 55, businessName: "Durgan Ltd", description: "Grass-roots upward-trending framework", floor: 5, building: "Black Gardens" },
        { baseAddressId: 55, businessName: "Zboncak Group PLC", description: "Reverse-engineered stable adapter", floor: 6, building: "Black Gardens" },
        { baseAddressId: 60, businessName: "Purdy, Orn and Spinka Group", description: "Quality-focused analyzing synergy", floor: 7, building: "SpringGreen Mews" },
        { baseAddressId: 61, businessName: "Kovacek Ltd", description: "Re-contextualized fault-tolerant migration", floor: 8, building: "LightGreen Vale" },
        { baseAddressId: 62, businessName: "Ernser Inc", description: "Triple-buffered client-server encryption", floor: 1, building: "ForestGreen Place" },
        { baseAddressId: 63, businessName: "Schulist Group", description: "Down-sized national utilisation", floor: 5, building: "AliceBlue Grove" },
        { baseAddressId: 64, businessName: "Grimes-Witting PLC", description: "Decentralized clear-thinking encoding", floor: 9, building: "SandyBrown Square" },
        { baseAddressId: 65, businessName: "Littel-Wunsch Inc", description: "Digitized content-based application", floor: 7, building: "Moccasin Gardens" },
        { baseAddressId: 66, businessName: "Green PLC", description: "Robust foreground opensystem", floor: 9, building: "SeaShell Mews" },
        { baseAddressId: 67, businessName: "Beer and Sons", description: "Multi-lateral 4thgeneration time-frame", floor: 8, building: "CadetBlue Vale" },
        { baseAddressId: 68, businessName: "Wilderman-Haley Group", description: "Multi-lateral local standardization" },
        { baseAddressId: 69, businessName: "Huel, Marks and Treutel LLC", description: "Business-focused tangible focusgroup" },
        { baseAddressId: 70, businessName: "Dickens, West and Heidenreich Group", description: "Cross-group zerodefect algorithm" },
        { baseAddressId: 71, businessName: "Mueller-Lubowitz Group", description: "Triple-buffered attitude-oriented installation", floor: 3, building: "Navy Gardens" },
        { baseAddressId: 72, businessName: "Hara-Blick Ltd", description: "Polarised asynchronous workforce", floor: 1, building: "Gray Mews" },
        { baseAddressId: 73, businessName: "Huels Group", description: "Stand-alone 3rdgeneration implementation", floor: 5, building: "AntiqueWhite Vale" },
        { baseAddressId: 74, businessName: "Ziemann-Torphy Ltd", description: "Monitored uniform architecture", floor: 4, building: "Gainsboro Place" },
        { baseAddressId: 60, businessName: "Rowe, Haag and Ryan LLC", description: "Ameliorated 5thgeneration matrix", floor: 6, building: "SpringGreen Mews" },
        { baseAddressId: 61, businessName: "Buckridge, Schoen and Abshire", description: "Business-focused logistical knowledgebase", floor: 2, building: "LightGreen Vale" },
        { baseAddressId: 62, businessName: "Prohaska Group", description: "Diverse didactic orchestration", floor: 4, building: "ForestGreen Place" },
        { baseAddressId: 63, businessName: "Hudson-Powlowski and Sons", description: "Polarised object-oriented workforce", floor: 5, building: "AliceBlue Grove" },
        { baseAddressId: 64, businessName: "Torphy-Rippin LLC", description: "Multi-channelled mission-critical processimprovement", floor: 7, building: "SandyBrown Square" },
        { baseAddressId: 65, businessName: "Jacobs Group", description: "Facetoface incremental superstructure", floor: 2, building: "Moccasin Gardens" },
        { baseAddressId: 66, businessName: "Marvin-Lebsack PLC", description: "Synergized user-facing adapter", floor: 7, building: "SeaShell Mews" },
        { baseAddressId: 67, businessName: "Greenfelder Inc", description: "Persistent context-sensitive migration", floor: 1, building: "CadetBlue Vale" },
        { baseAddressId: 68, businessName: "Greenholt PLC", description: "Cloned logistical infrastructure" },
        { baseAddressId: 69, businessName: "Shanahan LLC", description: "Configurable bandwidth-monitored archive" },
        { baseAddressId: 70, businessName: "Hamill-Schuppe Inc", description: "Customizable web-enabled extranet" },
        { baseAddressId: 71, businessName: "Monahan-Rau PLC", description: "Fully-configurable non-volatile productivity", floor: 4, building: "Navy Gardens" },
        { baseAddressId: 72, businessName: "Schmidt PLC", description: "Decentralized empowering emulation", floor: 3, building: "Gray Mews" },
        { baseAddressId: 73, businessName: "Mante, Dietrich and Hamill Ltd", description: "De-engineered assymetric localareanetwork", floor: 5, building: "AntiqueWhite Vale" },
        { baseAddressId: 74, businessName: "Leannon and Sons and Sons", description: "Adaptive zerotolerance openarchitecture", floor: 8, building: "Gainsboro Place" }
    ]));
}

function migrateFarmAddress() {
    return FarmAddress.sync({ force: true }).then(() => FarmAddress.bulkCreate([
        { baseAddressId: 1, farmName: "Mr. Sienna's Farm", areaDescription: "opposite farm dam" },
        { baseAddressId: 2, farmName: "Mr. SeaGreen's Farm", areaDescription: "next to the cow" },
        { baseAddressId: 3, farmName: "Prof. Green's Farm", areaDescription: "adjacent to grass" },
        { baseAddressId: 4, farmName: "Prof. Dark's Farm", areaDescription: "near tree" },
        { baseAddressId: 5, farmName: "Mr. LightGreen's Farm", areaDescription: "against bird's nest" },
        { baseAddressId: 6, farmName: "Dr. Pink's Farm", areaDescription: "opposite rabid boars" },
        { baseAddressId: 7, farmName: "Dr. Cornflower's Farm", areaDescription: "in shadow of avalanche" },
        { baseAddressId: 8, farmName: "Ms. MintCream's Farm", areaDescription: "betwixt a rock and a hard place" },
        { baseAddressId: 9, farmName: "Mrs. FireBrick's Farm", areaDescription: "between death and life" },
        { baseAddressId: 10, farmName: "Prof. Navy's Farm", areaDescription: "in a tough spot" },
        { baseAddressId: 11, farmName: "Mr. Forest's Farm", areaDescription: "in doubt" },
        { baseAddressId: 12, farmName: "Ms. Red's Farm", areaDescription: "on top of its game" },
        { baseAddressId: 13, farmName: "Ms. Indian's Farm", areaDescription: "below average" },
        { baseAddressId: 14, farmName: "Prof. Orchid's Farm", areaDescription: "under performing" },
        { baseAddressId: 15, farmName: "Mrs. Yellow's Farm", areaDescription: "besides itself" },
        { baseAddressId: 16, farmName: "Ms. Azure's Farm", areaDescription: "next to the hen" },
        { baseAddressId: 17, farmName: "Mrs. SlateBlue's Farm", areaDescription: "next to the pig" },
        { baseAddressId: 18, farmName: "Ms. LightCoral's Farm", areaDescription: "next to the dog" },
        { baseAddressId: 19, farmName: "Sir. Gray's Farm", areaDescription: "next to the cat" },
        { baseAddressId: 20, farmName: "Mr. Chocolate's Farm", areaDescription: "next to the sheep" }
    ]));
}